### ISSUE TITLE
Service account permission issue while accessing secret from external eks cluster

### ISSUE THREAD

**Issue by anishraut7836** [hashicorp-education/learn-vault-secrets-operator#10]
{"level":"error","ts":"2024-08-08T15:21:14Z","logger":"cachingClientFactory","msg":"Failed to get NewClientWithLogin","controller":"vaultstaticsecret","controllerGroup":"secrets.hashicorp.com","controllerKind":"VaultStaticSecret","VaultStaticSecret":{"name":"vault-kv-app","namespace":"app"},"namespace":"app","name":"vault-kv-app","reconcileID":"dc84d3a8-bd0f-4242-b32b-5c0b99f7fa21","cacheKey":"kubernetes-c450f6ef1f5c12cff57fdf","error":"Error making API request.\n\nURL: PUT https://myvaulturl/v1/auth/preprod-auth-mount/login\nCode: 403. Errors:\n\n* permission denied"}

**Comment by mister-ken** [comment]
@anishraut7836 This repo is in support of the tutorial [The Vault Secrets Operator on Kubernetes](https://developer.hashicorp.com/vault/tutorials/kubernetes/vault-secrets-operator#prerequisites) and mich is meant to be an example of VSO with Minikube.  **The tutorial does not support EKS.**  

You would want to talk to your HashiCorp representative, or at the an online forum like [HashiCorp Vault Discuss](https://discuss.hashicorp.com/c/vault/30).

In the meantime I'm closing the issue.
